### ISSUE TITLE
DPC changed site in https.

### ISSUE THREAD

**Issue by caiosweet** [gpirrotta/protezionecivilepop#10]
Hello. The DPC site is now in https and all the data is also on github. Will this project continue to work and be updated?
Thanks for your attention.

[New site https](https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita)

[Github Source](https://github.com/pcm-dpc/DPC-Bollettini-Criticita-Idrogeologica-Idraulica/tree/master/files)

**Comment by gpirrotta** [comment]
Hi, 
yes, the service has to be refactored because of new data source but I can't tell a date.
Thank you for your feedback.

**Comment by 0limits91** [comment]
Hi Giovanni, 
First of all, thank you for the service you offer (I don't use it personally but the issue is very close to my heart).
I created a simple script for reading weather reports (dpc) from the github repository based on shape files. I am attaching the link of the repository if it can be of help for the refactoring of your service.

https://github.com/0limits91/dpc-allerta-meteo/tree/main/v2

Currently there is no caching and db system and the code should be revised as it was written quickly.

Best Regards, 
Francesco

**Comment by gpirrotta** [comment]
The service is online again. Thanks for your feedback!
